apiVersion: v1
kind: Service
metadata:
  name: movies
spec:
  type: ClusterIP      
  ports:
    - port: 80         # порт по якому можна звератись до сервісу
      targetPort: 8080 # порт контейнера
  selector:
    app: movies      # селектор, всі Pod з даним селектором, будуть підключені до даного сервісу